spring:
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      maxFilesize: 10MB
      maxRequestSize: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:h2:mem:dodam
    driver-class-name: org.h2.Driver
    username: sa
    password:
  # datasource:
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   url: jdbc:mysql://database-3.cyggh9yzs5m7.ap-northeast-2.rds.amazonaws.com:3306/database3
  #   username: admin
  #   password: asdf1234

  # mail:
  #   host: smtp.gmail.com
  #   port: 587
  #   username: team3mailsender@gmail.com
  #   password: hgmhkhaodqcxtpyu
  #   properties:
  #     mail:
  #       smtp:
  #         auth: true
  #         starttls:
  #           enable: true

  # redis:
  #   host: localhost
  #   password:
  #   port: 6379
  #   jedis:
  #     pool:
  #       max-idle: 8
  #       min-idle: 0
  #       max-active: 8
  #       max-wait: -1



  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   properties:
  #     hibernate:
  #       default_batch_fetch_size: 10

  # # 이메일 발송시 사용하는 html 템플릿 설정
  # ## thymeleaf default settings
  # thymeleaf:
  #   prefix: classpath:/mail-templates/ # 이메일 템플릿이 위치할 경로. classpath:를 통해 src/main/resources/ 밑으로 설정되었다.
  #   suffix: .html # 템플릿 파일의 확장자
  #   mode: HTML
  #   encoding: UTF-8
  #   check-template-location: true
  # ## thymeleaf custom settings
  #   cache: false

server:
  error:
    include-exception: false # Response? Exception ?? ??
    include-message: always # Response? Exception Message ?? ??
    include-stacktrace: on_param # Response? Stack Trace ?? ??
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

cloud:
  aws:
    credentials:
      access-key: AKIA35FVUZKRV7SXAYV4
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: bondyu

jwt:
  secret: 4oCYc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWhhbmdoYWUtYXNzaWdubWVudC1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3Qtc2VjcmV0LWtleeKAmQo=
# echo 'spring-boot-security-jwt-hanghae-assignment-spring-boot-security-jwt-secret-key' | base64
